#! /bin/sh
### BEGIN INIT INFO
# Provides:          cpi_resize
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Resize FAT partition and filesystem
# Description:       Resize FAT partition and filesystem
### END INIT INFO

# Author: Harald Latzko <h.latzko@os4x.com>
#
# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Resize FAT partition and filesystem"
NAME=cpi_resize
TOOL=/opt/selector/tools/cpi_resize.sh

# Exit if the package is not installed
[ -x "$TOOL" ] || exit 0

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

case "$1" in
  start)
	$TOOL 
	log_end_msg 0 ;;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start}" >&2
	exit 3
	;;
esac

