#! /usr/bin/python
# -*- coding: utf-8 -*-

from pygame.locals import *

FONT_NAME = "resources/font/Orbitron-Regular.ttf"
FONT_NAME2 = "resources/font/QuattrocentoSans-Regular.ttf"

SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080


# se référer à pygame.locals pour savoir les touche
KEY_DIR_LEFT = K_LEFT
KEY_DIR_RIGHT = K_RIGHT
KEY_DIR_UP = K_UP
KEY_DIR_DOWN = K_DOWN
KEY_BUT_VALIDATE = K_RETURN
KEY_BUT_EXIT = K_ESCAPE
KEY_BUT_SCROLL_DOWN = K_PAGEDOWN
KEY_BUT_SCROLL_UP = K_PAGEUP
KEY_BUT_EXIT_FOR_BASH = K_t
KEY_BUT_OPTION_MENU = K_o
KEY_BUT_CHOOSE_EMULATOR_1 = K_1
KEY_BUT_CHOOSE_EMULATOR_2 = K_2
KEY_BUT_CHOOSE_EMULATOR_3 = K_3
KEY_BUT_SHUTDOWN = K_q
KEY_BUT_SCREENSAVER = K_j
KEY_BUT_SHOW_INFO = K_k

KEY_BUT_HELP_EMULATOR_OFFI = K_w
KEY_BUT_HELP_ENGINE = K_c
KEY_BUT_HELP_EMULATOR = K_e
KEY_BUT_HELP_CHAMELEON = K_h